package migrator

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
)

func Lower(program Program, sourcePath string, sourceRaw []byte) (SemanticIR, error) {
	if err := program.Validate(); err != nil {
		return SemanticIR{}, err
	}
	execution, err := Execute(program)
	if err != nil {
		return SemanticIR{}, err
	}
	canonical := program.canonical()
	ir := SemanticIR{
		Schema: ProgramSchemaToIR(), ProgramID: canonical.ID, Dialect: canonical.Dialect, SourcePath: sourcePath,
		SourceDigest: DigestBytes(sourceRaw), Nodes: canonical.Nodes, Edges: canonical.Edges, Entry: canonical.Entry,
		TerminalReason: execution.TerminalReason, CapabilitySet: execution.CapabilitySet, EffectTrace: execution.EffectTrace,
	}
	ir.SemanticDigest = ir.CanonicalDigest()
	return ir, nil
}

func ProgramSchemaToIR() string { return IRSchema }

func Execute(program Program) (Execution, error) {
	if err := program.Validate(); err != nil {
		return Execution{}, err
	}
	nodes := make(map[string]Node, len(program.Nodes))
	for _, node := range program.Nodes {
		nodes[node.ID] = node
	}
	next := make(map[string][]string)
	for _, edge := range program.Edges {
		next[edge.From] = append(next[edge.From], edge.To)
	}
	for key := range next {
		sortStrings(next[key])
	}
	current := program.Entry
	visited := map[string]bool{}
	var effects []string
	var capabilities []string
	for steps := 0; steps <= len(nodes); steps++ {
		if visited[current] {
			return Execution{}, fmt.Errorf("program execution contains a cycle at %s", current)
		}
		visited[current] = true
		node := nodes[current]
		capabilities = append(capabilities, node.Capabilities...)
		effects = append(effects, node.Effects...)
		outgoing := next[current]
		if len(outgoing) == 0 {
			return Execution{TerminalReason: program.TerminalReason, EffectTrace: effects, CapabilitySet: sortedUnique(capabilities)}, nil
		}
		if len(outgoing) != 1 {
			return Execution{}, fmt.Errorf("execution is ambiguous at %s: %d outgoing edges", current, len(outgoing))
		}
		current = outgoing[0]
	}
	return Execution{}, errors.New("program execution exceeded node bound")
}

func RenderProgram(program Program, comment string) ([]byte, error) {
	if err := program.Validate(); err != nil {
		return nil, err
	}
	program = program.canonical()
	var out strings.Builder
	out.WriteString("gooo program v1\n")
	out.WriteString("program id=" + program.ID + " dialect=" + program.Dialect + " entry=" + program.Entry + "\n")
	if comment != "" {
		out.WriteString("# " + comment + "\n")
	}
	for _, node := range program.Nodes {
		out.WriteString("node id=" + node.ID + " symbol=" + node.Symbol + " capabilities=" + listValue(node.Capabilities) + " effects=" + listValue(node.Effects) + "\n")
	}
	for _, edge := range program.Edges {
		out.WriteString("edge from=" + edge.From + " to=" + edge.To + "\n")
	}
	out.WriteString("terminal reason=" + program.TerminalReason + "\n")
	return []byte(out.String()), nil
}

func RenderIR(ir SemanticIR) ([]byte, error) {
	canonical := ir.canonical()
	canonical.SemanticDigest = canonical.CanonicalDigest()
	return json.MarshalIndent(canonical, "", "  ")
}

func RenderBinding(ir SemanticIR, packageName string) ([]byte, error) {
	raw, err := RenderIR(ir)
	if err != nil {
		return nil, err
	}
	binding := GeneratedBinding{Schema: BindingSchema, ProgramID: ir.ProgramID, Dialect: ir.Dialect, SourceDigest: ir.SourceDigest, SemanticDigest: ir.SemanticDigest}
	bindingRaw, err := json.Marshal(binding)
	if err != nil {
		return nil, err
	}
	var out strings.Builder
	out.WriteString("// Code generated by the gooo semantic dialect migrator; DO NOT EDIT.\n")
	out.WriteString("package " + packageName + "\n\n")
	suffix := strings.ToUpper(ir.Dialect)
	out.WriteString("const BindingJSON" + suffix + " = ")
	out.WriteString(strconv.Quote(string(bindingRaw)))
	out.WriteString("\nconst CanonicalIRJSON" + suffix + " = ")
	out.WriteString(strconv.Quote(string(raw)))
	out.WriteString("\n")
	return []byte(out.String()), nil
}

func ParseIR(raw []byte) (SemanticIR, error) {
	var ir SemanticIR
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&ir); err != nil {
		return SemanticIR{}, err
	}
	if ir.Schema != IRSchema || ir.ProgramID == "" || ir.SemanticDigest == "" || ir.SemanticDigest != ir.CanonicalDigest() {
		return SemanticIR{}, errors.New("semantic IR identity or digest is invalid")
	}
	return ir, nil
}

func listValue(values []string) string {
	if len(values) == 0 {
		return "-"
	}
	return strings.Join(values, "|")
}

func sortStrings(values []string) {
	for i := 0; i < len(values); i++ {
		for j := i + 1; j < len(values); j++ {
			if values[j] < values[i] {
				values[i], values[j] = values[j], values[i]
			}
		}
	}
}
